# Generated by Django 3.0.3 on 2020-03-01 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_img_lkce'),
    ]

    operations = [
        migrations.RenameField(
            model_name='img_lkce',
            old_name='lkce_Main_Img',
            new_name='Images',
        ),
    ]
