# Generated by Django 3.0.3 on 2020-03-03 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20200301_0257'),
    ]

    operations = [
        migrations.CreateModel(
            name='newspaper_lkce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newspaperPictures', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
