# Generated by Django 3.0.3 on 2020-03-03 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_newspaper_lkce'),
    ]

    operations = [
        migrations.CreateModel(
            name='newsletter_lkce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newsletters', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
