# Generated by Django 3.0.3 on 2020-03-03 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_newsletter_lkce'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter_lkce',
            name='newsletters',
            field=models.FileField(upload_to='images/'),
        ),
    ]
