# Generated by Django 3.0.3 on 2020-03-03 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20200303_0836'),
    ]

    operations = [
        migrations.CreateModel(
            name='newsletters_lkce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('newsletters', models.FileField(upload_to='images/')),
            ],
        ),
        migrations.DeleteModel(
            name='newsletter_lkce',
        ),
    ]
