# Generated by Django 3.0.3 on 2020-03-05 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20200303_0858'),
    ]

    operations = [
        migrations.CreateModel(
            name='newsletterss_lkce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('newsletters', models.FileField(upload_to='images/')),
            ],
        ),
        migrations.DeleteModel(
            name='newsletters_lkce',
        ),
    ]
