# Generated by Django 3.0.3 on 2020-03-12 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_events_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='student_placed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='images/')),
                ('student_name', models.CharField(max_length=50)),
                ('roll_no', models.CharField(max_length=50)),
                ('stream', models.CharField(max_length=50)),
                ('company_name', models.CharField(max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
