# Generated by Django 3.0.3 on 2020-05-10 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_stream_add_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedback_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=300)),
                ('subject', models.CharField(max_length=250)),
                ('phone', models.CharField(max_length=500)),
                ('message', models.TextField(max_length=700)),
            ],
        ),
    ]
