# Generated by Django 3.0.3 on 2020-05-10 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_feedback_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='academic_calender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('calender', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
